In [64]:
import tensorflow as tf
import numpy as np 

from tensorflow import keras
from tensorflow.keras.preprocessing import image

In [3]:
print(tf.__version__)

2.16.1


In [4]:
(train_images, train_labels), (test_images, test_labels) = keras.datasets.mnist.load_data()

In [54]:
print("train images")
print("amount", len(train_images))

print(len(train_images[0]))
print(len(train_images[0][0]))
print(train_images)

train images
amount 60000
28
28
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [46]:
print("train labels")
print(train_labels)

train labels
[5 0 4 ... 5 6 8]


In [20]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation=tf.nn.softmax),
])

model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_14 (Flatten)            │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile(
    optimizer="adam",
    loss=keras.losses.SparseCategoricalCrossentropy(),
    metrics=["accuracy"],
)

In [26]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 960us/step - accuracy: 0.8077 - loss: 8.2836
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 978us/step - accuracy: 0.9028 - loss: 0.4025
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 989us/step - accuracy: 0.9252 - loss: 0.2928
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9376 - loss: 0.2436
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9444 - loss: 0.2221


In [27]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print("loss", test_loss)
print("acc", test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - accuracy: 0.9292 - loss: 0.2780
loss 0.24821269512176514
acc 0.9369000196456909


In [35]:
test_images[0] # image is 28x28 matrix

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [61]:
predictions = model.predict(test_images)
predictions

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step


array([[0.00000000e+00, 7.88977550e-10, 4.82050268e-07, ...,
        9.99998093e-01, 1.26592991e-16, 5.18140565e-12],
       [3.35450447e-23, 3.71316086e-12, 1.00000000e+00, ...,
        7.38992240e-17, 6.58479388e-20, 0.00000000e+00],
       [4.52256890e-29, 9.99775708e-01, 5.54624657e-09, ...,
        2.24308562e-04, 2.60580498e-11, 6.96646135e-19],
       ...,
       [1.98189085e-29, 3.65623981e-12, 1.10806475e-07, ...,
        1.40278253e-05, 1.27818993e-07, 3.97998048e-03],
       [1.14773300e-19, 2.80506377e-21, 1.70508833e-19, ...,
        2.37914983e-11, 1.29226319e-08, 4.91958176e-15],
       [2.54957467e-06, 1.47217931e-13, 1.72512282e-05, ...,
        4.90865927e-15, 7.47579278e-08, 7.54025177e-26]], dtype=float32)

In [76]:
img = image.load_img("number.png", color_mode="grayscale", target_size=(28, 28))

In [78]:
# Convert the image to a numpy array
img_array = image.img_to_array(img)

print(img_array, len(img_array), len(img_array[0]))

# Normalize the image array
img_array = img_array / 255.0  # Model dependent: some models expect inputs in range [0, 1], others in [-1, 1]

print(img_array, len(img_array), len(img_array[0]))

# Add a batch dimension
img_array = np.expand_dims(img_array, axis=0)  # Model expects shape (batch_size, height, width, channels)

img_array

[[[255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]]

 [[255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [239.]
  [239.]
  [239.]
  [111.]
  [111.]
  [111.]
  [ 15.]
  [ 15.]
  [ 15.]
  [ 79.]
  [ 79.]
  [ 79.]
  [207.]
  [207.]
  [207.]
  [239.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]]

 [[255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [239.]
  [239.]
  [239.]
  [111.]
  [111.]
  [111.]
  [ 15.]
  [ 15.]
  [ 15.]
  [ 79.]
  [ 79.]
  [ 79.]
  [207.]
  [207.]
  [207.]
  [239.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]]

 [[255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [255.]
  [239.]
  [239.]
  [239.]
  [111.]
  [111.]
  [111.]
  [ 15.]
  [ 15.]
  [ 15.]
  [ 79.]
  [ 79.]
  [ 79.]
  [207.]
  [207.]
  [207.]
  [239.]
  [255.]
  [255.]
  [255.]
  [255.]
  [2

array([[[[1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ]],

        [[1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [1.        ],
         [0.9372549 ],
         [0.9372549 ],
         [0.9372549 ],
         [0.43529412],
         [0.43529412],
         [0.43529412],
         [0.05882353],
         [0.05882353],
         [0.05882353],
         

In [84]:
predictions = model.predict(img_array)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
[[0.12299188 0.07921141 0.0711053  0.10729959 0.07679918 0.08752335
  0.06668793 0.07589417 0.12792625 0.18456095]]


0.18456095

In [83]:
# For classification, you might want to get the class with the highest probability
predicted_class = np.argmax(predictions, axis=-1)
print("Predicted Class:", predicted_class)

Predicted Class: [9]
